apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: radarr-cors
  namespace: apps-radarr
spec:
  headers:
    accessControlAllowOriginList:
      - https://homer.rancher.tailscale.bnowakowski.pl
      - https://homer.rancher.localdomain.bnowakowski.pl
    accessControlAllowMethods:
      - GET
      - OPTIONS
    accessControlAllowHeaders:
      - X-Api-Key
      - Authorization
      - Content-Type
    accessControlMaxAge: 600
    addVaryHeader: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr-tailscale-cors
  namespace: apps-radarr
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`radarr.rancher.tailscale.bnowakowski.pl`)
      priority: 100
      middlewares:
        - name: radarr-cors
      services:
        - name: radarr
          port: main
  tls:
    secretName: radarr-tls-0
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr-localdomain-cors
  namespace: apps-radarr
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`radarr.rancher.localdomain.bnowakowski.pl`)
      priority: 100
      middlewares:
        - name: radarr-cors
      services:
        - name: radarr
          port: main
  tls:
    secretName: radarr-tls-1
