apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-config-longhorn-rwx
  namespace: apps-homer
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
