apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn
  namespace: kube-system
spec:
  repo: https://charts.longhorn.io
  chart: longhorn
  version: 1.12.0
  targetNamespace: longhorn-system
  createNamespace: true
  failurePolicy: abort
  valuesContent: |-
    defaultBackupStore:
      backupTarget: nfs://nas.localdomain.bnowakowski.pl:/mnt/MargokPool/archive/Backups/rancher/longhorn

    defaultSettings:
      createDefaultDiskLabeledNodes: true
      defaultDataPath: /var/lib/longhorn
      defaultReplicaCount: 2
      storageReservedPercentageForDefaultDisk: 10

    persistence:
      defaultClass: false
      defaultClassReplicaCount: 2
      reclaimPolicy: Retain
