persistence:
  output:
    enabled: false
    mountPath: /output
  storage:
    enabled: true
    path: /mnt/PlexPool/plex
    server: nas.localdomain.bnowakowski.pl
    type: nfs
    mountPath: /storage
  watch:
    enabled: false
    mountPath: /watch
