[k3s_servers]
proxmox3 ansible_host=proxmox3.localdomain.bnowakowski.pl k3s_init=true
proxmox2-old ansible_host=proxmox2-old.localdomain.bnowakowski.pl

[k3s_agents]
# proxmox5 ansible_host=10.0.0.52

[longhorn_nodes]
proxmox3
proxmox2-old

[all:vars]
ansible_user=sup
ansible_become=true

