# Debian logrotate config for helm-upgrade-apps logs
# Install to: /etc/logrotate.d/helm-upgrade-apps
# This file is a template. Install it using:
#   ./install-logrotate-helm-upgrade-apps.sh

__LOG_GLOB__ {
    daily
    rotate 30
    maxage 90
    missingok
    notifempty
    compress
    delaycompress
}
