apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: jellyseerr-cors
  namespace: apps-jellyseerr
spec:
  headers:
    accessControlAllowOriginList:
      - https://homer.rancher.tailscale.bnowakowski.pl
      - https://homer.rancher.localdomain.bnowakowski.pl
    accessControlAllowMethods:
      - GET
      - OPTIONS
    accessControlAllowHeaders:
      - X-Api-Key
      - Content-Type
    accessControlMaxAge: 600
    addVaryHeader: true
