ingressMiddlewares:
  traefik:
    jellyseerr-cors:
      enabled: true
      type: headers
      data:
        accessControlAllowOriginList:
          - https://homer.rancher.tailscale.bnowakowski.pl
          - https://homer.rancher.localdomain.bnowakowski.pl
        accessControlAllowMethods:
          - GET
          - OPTIONS
        accessControlAllowHeaders:
          - X-Api-Key
          - Content-Type
        accessControlMaxAge: 600
        addVaryHeader: true

persistence:
  config:
    existingClaim: jellyseerr-config

ingress:
  main:
    enabled: true
    primary: true
    ingressClassName: traefik
    hosts:
      - host: jellyseerr.rancher.tailscale.bnowakowski.pl
        paths:
          - path: /
            pathType: Prefix
      - host: jellyseerr.rancher.localdomain.bnowakowski.pl
        paths:
          - path: /
            pathType: Prefix
    integrations:
      certManager:
        enabled: true
        certificateIssuer: letsencrypt
      traefik:
        enabled: true
        entrypoints:
          - websecure
        forceTLS: true
        middlewares:
          - name: jellyseerr-cors
            namespace: apps-jellyseerr
