apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-test-config-longhorn-rwx
  namespace: apps-homer-test
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1273Ki
