name: longhorn
defaultNamespace: longhorn-system

helm:
  repo: https://charts.longhorn.io
  chart: longhorn
  version: 1.12.0
      releaseName: longhorn
      waitForJobs: true
      atomic: false
      valuesFiles:
    - values.yaml
