defaultBackupStore:
  backupTarget: nfs://nas.localdomain.bnowakowski.pl:/mnt/MargokPool/archive/Backups/rancher/longhorn

defaultSettings:
  createDefaultDiskLabeledNodes: true
  defaultDataPath: /var/lib/longhorn
  defaultReplicaCount: 2
  storageReservedPercentageForDefaultDisk: 10

persistence:
  defaultClass: false
  defaultClassReplicaCount: 2
  reclaimPolicy: Retain
