defaultBackupStore:
  backupTarget: nfs://nas.localdomain.bnowakowski.pl:/mnt/MargokPool/archive/Backups/rancher/longhorn

defaultSettings:
  # The single remaining node should receive Longhorn's default disk automatically.
  createDefaultDiskLabeledNodes: false
  defaultDataPath: /var/lib/longhorn
  defaultReplicaCount: 1
  storageReservedPercentageForDefaultDisk: 10

persistence:
  defaultClass: false
  defaultClassReplicaCount: 1
  reclaimPolicy: Retain
