apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bindery.fullname" . }}-tailscale
  labels:
    {{- include "bindery.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: traefik
  tls:
    - secretName: {{ include "bindery.fullname" . }}-tailscale-tls
      hosts:
        - bindery.rancher.tailscale.bnowakowski.pl
  rules:
    - host: bindery.rancher.tailscale.bnowakowski.pl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "bindery.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bindery.fullname" . }}-localdomain
  labels:
    {{- include "bindery.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: traefik
  tls:
    - secretName: {{ include "bindery.fullname" . }}-localdomain-tls
      hosts:
        - bindery.rancher.localdomain.bnowakowski.pl
  rules:
    - host: bindery.rancher.localdomain.bnowakowski.pl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "bindery.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
