apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: homer-config-authelia
  namespace: apps-homer
spec:
  forwardAuth:
    address: http://authelia.apps-authelia.svc.cluster.local:9091/api/authz/forward-auth
    trustForwardHeader: true
    authResponseHeaders:
      - Remote-User
      - Remote-Groups
      - Remote-Email
      - Remote-Name
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homer-config-tailscale-auth
  namespace: apps-homer
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`homer.rancher.tailscale.bnowakowski.pl`)
      priority: 1000
      middlewares:
        - name: homer-config-authelia
      services:
        - name: homer
          port: main
  tls:
    secretName: homer-tls-0
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homer-config-localdomain-auth
  namespace: apps-homer
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`homer.rancher.localdomain.bnowakowski.pl`)
      priority: 1000
      middlewares:
        - name: homer-config-authelia
      services:
        - name: homer
          port: main
  tls:
    secretName: homer-tls-1
