persistence:
  path1:
    enabled: true
    type: pvc
    storageClass: local-path
    size: 20Gi
    mountPath: /root/.local/share/Mailpile
  path2:
    enabled: true
    type: pvc
    storageClass: local-path
    size: 1Gi
    mountPath: /root/.gnupg

ingress:
  main:
    enabled: true
    primary: true
    ingressClassName: traefik
    hosts:
      - host: mailpile.rancher.tailscale.bnowakowski.pl
        paths:
          - path: /
            pathType: Prefix
      - host: mailpile.rancher.localdomain.bnowakowski.pl
        paths:
          - path: /
            pathType: Prefix
    integrations:
      certManager:
        enabled: true
        certificateIssuer: letsencrypt
      traefik:
        enabled: true
        entrypoints:
          - websecure
        forceTLS: true
