apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    dashboard:
      enabled: true
    ports:
      web:
        hostPort: 80
      websecure:
        hostPort: 443
      traefik:
        expose:
          default: true
    logs:
      access:
        enabled: true
    deployment:
      replicas: 2
      podAnnotations:
        prometheus.io/port: "8082"
        prometheus.io/scrape: "true"
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: traefik
                  app.kubernetes.io/instance: traefik-kube-system
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: traefik
            app.kubernetes.io/instance: traefik-kube-system
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
    priorityClassName: system-cluster-critical
    image:
      repository: rancher/mirrored-library-traefik
      tag: "3.7.8"
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
