apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-home-config-longhorn
  namespace: apps-adguard-home
  labels:
    app.kubernetes.io/part-of: adguard-home-migration
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-home-data-longhorn
  namespace: apps-adguard-home
  labels:
    app.kubernetes.io/part-of: adguard-home-migration
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
