# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bnowakow/home-assistant"
  config.vm.box_version = "9.5"

  config.vm.box_check_update = true

  # HA frontend
  config.vm.network "forwarded_port", guest: 8123, host: 8123, auto_correct: true
  # mqtt
  config.vm.network "forwarded_port", guest: 1883, host: 1883, auto_correct: true
  config.vm.network "forwarded_port", guest: 1884, host: 1884, auto_correct: true
  config.vm.network "forwarded_port", guest: 8883, host: 8883, auto_correct: true
  config.vm.network "forwarded_port", guest: 8884, host: 8884, auto_correct: true
  # zigbee2mqtt
  config.vm.network "forwarded_port", guest: 8485, host: 8485, auto_correct: true
  config.vm.network "forwarded_port", guest: 8099, host: 8099, auto_correct: true
  # Bonjour
  config.vm.network "forwarded_port", guest: 5353, host: 5353, auto_correct: true
  # HomeKit
  config.vm.network "forwarded_port", guest: 21064, host: 21064, auto_correct: true 
  config.vm.network "forwarded_port", guest: 21066, host: 21066, auto_correct: true #Kasia workaround  
# Zabbix-agent
  config.vm.network "forwarded_port", guest: 10051, host: 10051, auto_correct: true
  # Let's encrypt
  config.vm.network "forwarded_port", guest: 8443, host: 8443

  # TODO solve boot_timeout issue where vagrant can't ssh to booting machine
  config.ssh.username="root"
  config.ssh.password="vagrant"
  # https://www.vagrantup.com/docs/vagrantfile/ssh_settings
  config.ssh.insert_key = true
  config.ssh.keys_only = false
  config.ssh.shell = "zsh"

  config.vm.network "public_network", bridge: "enp5s0f1" 

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 4 
    vb.memory = "10024"
  end

  # When restoring HA backup/snapshot: https://community.home-assistant.io/t/add-ons-not-working-properly-after-snapshot-restore/449796/18
  # https://github.com/zigbee2mqtt/hassio-zigbee2mqtt#installation
  # https://github.com/pschmitt/home-assistant-addons

end
