workload:
  main:
    podSpec:
      containers:
        main:
          env:
            LOG_FILE: false
            SUBDOMAINS: rancher-sup.duckdns.org
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
