application:
  port: 6868
  urlBase: ''

deployment:
  container:
    env:
      - name: PUID
        value: "1000"
      - name: PGID
        value: "1000"
      - name: TZ
        value: Europe/Warsaw
      - name: AUTH
        value: "on"
      - name: ORIGIN
        value: https://profilarr.rancher.tailscale.bnowakowski.pl
    volumeMounts:
      - name: config
        mountPath: /config
  volumes:
    config:
      persistentVolumeClaim:
        claimName: profilarr-config

persistentVolumeClaims:
  profilarr-config:
    accessMode: ReadWriteOnce
    requestStorage: 5Gi
    selector: {}

ingress:
  enabled: true
  className: traefik
  host: profilarr.rancher.tailscale.bnowakowski.pl
  path: /
  pathType: Prefix
  tls:
    - secretName: profilarr-tailscale-tls
      hosts:
        - profilarr.rancher.tailscale.bnowakowski.pl
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
