service:
  dns-tcp:
    enabled: true
    type: LoadBalancer
    ports:
      dns-tcp:
        enabled: true
        port: 53
        protocol: tcp
        targetPort: 53
  dns-udp:
    enabled: true
    type: LoadBalancer
    ports:
      dns-udp:
        enabled: true
        port: 53
        protocol: udp
        targetPort: 53

persistence:
  config:
    enabled: true
    type: pvc
    storageClass: local-path
    size: 100Mi
    existingClaim: adguard-home-config
    mountPath: /opt/adguardhome/conf
  data:
    enabled: true
    type: pvc
    storageClass: local-path
    size: 10Gi
    existingClaim: adguard-home-data
    mountPath: /opt/adguardhome/work

ingress:
  main:
    enabled: true
    primary: true
    ingressClassName: traefik
    hosts:
      - host: adguard-home.rancher.tailscale.bnowakowski.pl
        paths:
          - path: /
            pathType: Prefix
      - host: adguard-home.rancher.localdomain.bnowakowski.pl
        paths:
          - path: /
            pathType: Prefix
    integrations:
      certManager:
        enabled: true
        certificateIssuer: letsencrypt
      traefik:
        enabled: true
        entrypoints:
          - websecure
        forceTLS: true
