Vagrant.configure("2") do |config|
  # for some reason ssh key auth doesn't work on 22.04, using 20.04 instead
  config.vm.box = "bnowakow/nordvpn-torrent"
 
  config.vm.network "private_network", ip: "192.168.10.150"

  config.vm.provider "virtualbox" do |vb|
    # https://gist.github.com/shengslogar/979b79a4a1bfd4840f391119e7341efe
    vb.memory = 8048
#    vb.cpus = 4
#    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "40"]
  end

# was in basebox

  config.vm.provision "install docker and jdupes", type: "shell", inline: <<-SHELL
    # https://docs.docker.com/engine/install/ubuntu/
    apt-get remove docker docker-engine docker.io containerd runc
    apt-get install -y ca-certificates curl gnupg lsb-release
    mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update
    apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin jdupes

    # https://docs.docker.com/engine/install/linux-postinstall/
    usermod -aG docker vagrant
  SHELL

# /was in basebox

  config.vm.provision "connect to nfs with manual workaround - archive", type: "shell", inline: <<-SHELL
    if [ ! -d "/mnt/MargokPool/archive" ]; then
        mkdir -p /mnt/MargokPool/archive
    fi
    if [ $(mount | grep "/mnt/MargokPool/archive" | wc -l) -gt 0 ]; then
        umount /mnt/MargokPool/archive
    fi
    mount -vvv -o vers=3 10.0.2.2:/mnt/MargokPool/archive /mnt/MargokPool/archive
  SHELL

  # TODO do a function to do above and below
  config.vm.provision "connect to nfs with manual workaround - home", type: "shell", inline: <<-SHELL
    if [ ! -d "/mnt/MargokPool/home/sup" ]; then
        mkdir -p /mnt/MargokPool/home/sup
    fi
    if [ $(mount | grep "/mnt/MargokPool/home/sup" | wc -l) -gt 0 ]; then 
        umount /mnt/MargokPool/home/sup
    fi
    mount -vvv -o vers=3 10.0.2.2:/mnt/MargokPool/home/sup /mnt/MargokPool/home/sup
  SHELL

  config.vm.provision "configure transmission gui", type: "shell", inline: <<-SHELL
    echo disabled
    exit
    cd /mnt/MargokPool/home/sup/code/bash_configs/nas/time-machine
    ./2-deduplicate.sh
  SHELL
    
end
