apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: nas-daily-backup
  namespace: longhorn-system
spec:
  name: nas-daily-backup
  cron: "0 1 * * *"
  task: backup
  groups:
    - nas-backup
  retentionPolicy: count-based
  retain: 14
  concurrency: 1
  parameters:
    full-backup-interval: "7"
