# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bnowakow/home-assistant"
  config.vm.box_version = "9.2"

  # config.vm.box_check_update = false

  # HA frontend
  config.vm.network "forwarded_port", guest: 8123, host: 8123, auto_correct: true
  # mqtt
  config.vm.network "forwarded_port", guest: 1883, host: 1883, auto_correct: true
  config.vm.network "forwarded_port", guest: 1884, host: 1884, auto_correct: true
  config.vm.network "forwarded_port", guest: 8883, host: 8883, auto_correct: true
  config.vm.network "forwarded_port", guest: 8884, host: 8884, auto_correct: true
  # zigbee2mqtt
  config.vm.network "forwarded_port", guest: 8485, host: 8485, auto_correct: true
  config.vm.network "forwarded_port", guest: 8099, host: 8099, auto_correct: true
  # Bonjour
  config.vm.network "forwarded_port", guest: 5353, host: 5353
  # HomeKit
  config.vm.network "forwarded_port", guest: 21064, host: 21064 
  # Zabbix-agent
  config.vm.network "forwarded_port", guest: 10051, host: 10051

  # TODO solve boot_timeout issue where vagrant can't ssh to booting machine
  config.ssh.username="root"
  config.ssh.password="vagrant"
  # https://www.vagrantup.com/docs/vagrantfile/ssh_settings
  config.ssh.insert_key = true
  config.ssh.keys_only = false
  config.ssh.shell = "zsh"

  # config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.network "public_network", bridge: "enp6s18" 

  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2 
    vb.memory = "4024"
  end

  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
