name: cert-manager
defaultNamespace: cert-manager

helm:
  chart: oci://quay.io/jetstack/charts/cert-manager
  version: v1.19.4
  releaseName: cert-manager
  waitForJobs: true
  atomic: true
  values:
    crds:
      enabled: true
    startupapicheck:
      timeout: 5m
