UserParameter=bnowakow.rancher.k8s.is-helm-up-to-date[*],/etc/zabbix/zabbix_agent2.d/bash_configs/rancher/zabbix/is-helm-image-up-to-date.sh $1
UserParameter=bnowakow.rancher.k8s.is-zabbix-docker-image-up-to-date,/etc/zabbix/zabbix_agent2.d/bash_configs/rancher/zabbix/is-zabbix-docker-image-up-to-date.sh

