persistence:
  config:
    enabled: true
    type: pvc
    existingClaim: homer-test-config-longhorn-rwx
    mountPath: /www/assets

podOptions:
  defaultAffinity: false
  defaultSpread: false

workload:
  main:
    replicas: 2
    podSpec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: homer-test
              app.kubernetes.io/name: homer
              pod.name: main

ingress:
  main:
    enabled: true
    primary: true
    ingressClassName: traefik
    hosts:
      - host: homer-test.rancher.tailscale.bnowakowski.pl
        paths:
          - path: /
            pathType: Prefix
      - host: homer-test.rancher.localdomain.bnowakowski.pl
        paths:
          - path: /
            pathType: Prefix
    integrations:
      certManager:
        enabled: true
        certificateIssuer: letsencrypt
      traefik:
        enabled: true
        entrypoints:
          - websecure
        forceTLS: true
