persistence:
  plex-nfs-persistence:
    enabled: true
    path: /mnt/PlexPool/plex
    server: nas.localdomain.bnowakowski.pl
    type: nfs
    targetSelector:
      main:
        main:
          mountPath: /mnt/PlexPool/plex

resources:
  limits:
    cpu: 12000m
  requests:
    cpu: 30m

metrics:
  main:
    enabled: false
