apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-test-config
  namespace: apps-homer-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
