apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-test-1
  namespace: cert-manager
spec:
  secretName: letstecrpty-test-1
  issuerRef:
    name: letsencrypt-stg
    kind: ClusterIssuer
  commonName: 'le-test.rancher.localdomain.bnowakowski.pl'
  dnsNames:
  - "le-test.rancher.localdomain.bnowakowski.pl"
